apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    app: postgres
spec:
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: postgres