apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_URL
            - name: ZIP_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: ZIP_URL
      initContainers:
        - name: flyway-migration
          image: {{ .Values.initContainers.flyway.image }}
          env:
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: FLYWAY_URL
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: FLYWAY_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: FLYWAY_PASSWORD
            - name: FLYWAY_LOCATIONS
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: FLYWAY_LOCATIONS
            - name: FLYWAY_SCHEMAS
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: FLYWAY_SCHEMAS
        - name: invalid-container # Invalid container name to cause failure
          image: {{ .Values.invalid.image }} # This will fail due to missing value
          env:
            - name: INVALID_ENV
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: INVALID_KEY
