apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: myregistrykey
      initContainers:
        - name: flyway-migration
          image: {{ .Values.image.flywayMigration.repository }}:{{ .Values.image.flywayMigration.tag }}
          imagePullPolicy: Always
          env:
            - name: FLYWAY_URL
              value: "{{ .Values.secrets.flyway.url }}"
            - name: FLYWAY_USER
              value: "{{ .Values.secrets.flyway.user }}"
            - name: FLYWAY_PASSWORD
              value: "{{ .Values.secrets.flyway.password }}"
            - name: FLYWAY_LOCATIONS
              value: "{{ .Values.secrets.flyway.locations }}"
            - name: FLYWAY_SCHEMAS
              value: "{{ .Values.secrets.flyway.schemas }}"
          volumeMounts:
            - name: pgdata
              mountPath: /data
      containers:
        - name: app-container
          image: {{ .Values.image.cveProcessor.repository }}:{{ .Values.image.cveProcessor.tag }}
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: "{{ .Values.secrets.cveProcessor.dbUrl }}"
            - name: ZIP_URL
              value: "{{ .Values.secrets.cveProcessor.zipUrl }}"
          volumeMounts:
            - name: pgdata
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
