---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-kafkajob
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_USERNAME
              value: {{ .Values.kafka.username }}
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: KAFKA_PASSWORD
            - name: KAFKA_BROKER1
              value: {{ index .Values.kafka.brokers 0 }}
            - name: KAFKA_BROKER2
              value: {{ index .Values.kafka.brokers 1 }}
            - name: KAFKA_BROKER3
              value: {{ index .Values.kafka.brokers 2 }}
            - name: ZIP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: ZIP_URL
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.topic }}
      restartPolicy: Never
