---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-role1
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]