apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.storageClass.name | lower }}"
provisioner: "{{ .Values.storageClass.provisioner }}"
parameters:
  type: "{{ .Values.storageClass.parameters.type }}"
  fsType: "{{ .Values.storageClass.parameters.fsType }}"
  encrypted: "true"
  kmsKeyId: "{{ .Values.secrets.flyway.kmsKeyId }}"
