apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  KAFKA_PASSWORD: {{ .Values.secrets.kafkaPassword | b64enc | quote }}
  ZIP_URL: {{ .Values.secrets.ZIP_URL | b64enc | quote }}
