apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
data:
  DB_URL: {{ .Values.secrets.DB_URL | b64enc | quote }}
  ZIP_URL: {{ .Values.secrets.ZIP_URL | b64enc | quote }}
  FLYWAY_URL: {{ .Values.secrets.FLYWAY_URL | b64enc | quote }}
  FLYWAY_USER: {{ .Values.secrets.FLYWAY_USER | b64enc | quote }}
  FLYWAY_PASSWORD: {{ .Values.secrets.FLYWAY_PASSWORD | b64enc | quote }}
  FLYWAY_LOCATIONS: {{ .Values.secrets.FLYWAY_LOCATIONS | b64enc | quote }}
  FLYWAY_SCHEMAS: {{ .Values.secrets.FLYWAY_SCHEMAS | b64enc | quote }}
