---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default false }}
